# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_entered', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('type_amount', models.CharField(choices=[('cash', 'CASH'), ('PayPal', 'PAYPAL')], default='cash', max_length=5)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 4, 2, 19, 11, 13, 270038))),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('barcode', models.CharField(max_length=30)),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 4, 2, 19, 11, 13, 272358))),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 4, 2, 19, 11, 13, 271554))),
                ('units', models.IntegerField(default=0)),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supermarket', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Item')),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagRfid', models.CharField(max_length=64)),
                ('chatid', models.DecimalField(decimal_places=0, max_digits=12)),
                ('balance_actual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('username', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.User_Data'),
        ),
    ]
