# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 23, 45, 23, 526422)),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale_history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 23, 45, 23, 528304)),
        ),
        migrations.AlterField(
            model_name='shopping_history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 23, 45, 23, 527637)),
        ),
        migrations.AlterField(
            model_name='shopping_history',
            name='supermarket',
            field=models.CharField(choices=[('mercadona', 'MERCADONA'), ('lidl', 'LIDL'), ('otro', 'OTRO')], default='otro', max_length=9),
        ),
    ]
