# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20170402_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_history',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control.User_Data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 23, 59, 57, 24501)),
        ),
        migrations.AlterField(
            model_name='sale_history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 23, 59, 57, 26456)),
        ),
        migrations.AlterField(
            model_name='shopping_history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 23, 59, 57, 25776)),
        ),
    ]
