# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20170403_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 19, 52, 4, 504993)),
        ),
        migrations.AlterField(
            model_name='balance',
            name='type_amount',
            field=models.CharField(choices=[('cash', 'CASH'), ('PayPal', 'PAYPAL')], default='cash', max_length=6),
        ),
        migrations.AlterField(
            model_name='sale_history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 19, 52, 4, 506831)),
        ),
        migrations.AlterField(
            model_name='shopping_history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 4, 19, 52, 4, 506193)),
        ),
    ]
